config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'users/select' => 'users/registrations#select'
    get 'users/confirm_phone' => 'users/registrations#confirm_phone'
    get 'users/new_address' => 'users/registrations#new_address'
    post 'users/create_address' => 'users/registrations#create_address' # ここだけ自分で追記
    get 'users/completed' => 'users/registrations#completed'
  end

  resources :users, only: [:show]

  resources :items, only: [:index, :new, :create, :show, :edit,:update,:destroy]  do
    member do
      get "purchase_confirmation"
    end
    collection do
      get 'search'
    end
  end

  resources :categories, only: [:index, :show]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end

  resources :cards, only: [:index, :new]

end

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/shared/_footer.html.haml
%footer.footer
  .footer-top.horizontal-padding-15
    .footer-top-left
      .footer-top-left__top
        スマホでかんたんフリマアプリ
      .footer-top-left__bottom
        今すぐ無料ダウンロード！
      .footer-top-left__images
        = image_tag 'mercari_icon.png', class: "footer-top-left__images--mercari"
        = image_tag 'app-store.svg', class: "footer-top-left__images--phone"
        = image_tag 'google-play.svg', class: "footer-top-left__images--phone"
    =image_tag 'footer_phone.png', class: "footer-top-right"
  .footer-middle.horizontal-padding-15
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        メルカリについて
      .footer-middle-wrapper__bottom
        = link_to '会社概要（運営会社）' , '/'
        = link_to '採用情報' , '/'
        = link_to '公式ブログ' , '/'
        = link_to 'メルカリロゴ利用ガイドライン' , '/'
        %p
          = icon "fab", "twitter"
          = icon "fab", "facebook-square"
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        ヘルプ＆ガイド
      .footer-middle-wrapper__bottom
        = link_to 'メルカリガイド' , '/'
        = link_to 'らくらくメルカリ便' , '/'
        = link_to '大型メルカリ便' , '/'
        = link_to '車体取引ガイド' , '/'
        = link_to 'メルカリあんしん・あんぜん宣言！' , '/'
        = link_to '偽ブランド品撲滅への取り組み' , '/'
        = link_to 'メルカリボックス' , '/'
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        プライバシーと利用規約
      .footer-middle-wrapper__bottom
        = link_to 'プライバシーポリシー' , '/'
        = link_to 'メルカリ利用規約' , '/'
        = link_to 'あんしんスマホサポート制度に関する利用特約' , '/'
        = link_to 'コンプライアンスポリシー' , '/'
        = link_to '偽ブランド品撲滅への取り組み' , '/'
        = link_to 'メルカリボックス' , '/'
    .footer-middle-wrapper
      .footer-middle-wrapper__header
      .footer-middle-wrapper__bottom
        = link_to '個人データの安全管理に係る基本方針' , '/'
        = link_to '特定商取引に関する表記' , '/'
        = link_to '資金決済法に基づく表示' , '/'
        = link_to '法令順守と犯罪抑止のために' , '/'
    .footer-middle-wrapper
      .footer-middle-wrapper__header
        国
      .footer-middle-wrapper__bottom
        = link_to '日本' , '/'
        = link_to 'United States' , '/'
  .footer-bottom.horizontal-padding-15
    .footer-bottom__logo-copyright
      = image_tag 'logo-white.svg', class: "footer-bottom__logo-copyright--logo"
      %span.footer-bottom__logo-copyright--copyright
        © 2019 Mercari

app/views/shared/_header.html.haml
%header.header.horizontal-padding-15
  .header-top
    = link_to root_path do
      = image_tag 'logo.svg', class: "header-top__logo"
    = form_with url: "", method: :get, local: true  do |f|
      = f.search_field :name, name: "name_search", placeholder: "何かお探しですか?", class: "header-top__search"
      = f.hidden_field :name, name: "q[:hoge]"
      = button_tag type: 'submit', class:"header-top__loupe" do
        = icon "fas", "search"
  .header-bottom
    .header-bottom-left
      .header-bottom-left__button
        = link_to "" do
          = icon "fas", "list", class:"header-bottom-left__button--red"
          カテゴリーから探す
        -# .category-lists
        -#   -# ↓親カテゴリの表示ここから↓
        -#   .category-lists__list.parent
        -#     - Category.roots.each do |parent_category|
        -#       = link_to root_path, class:"category-lists__list--category" do
        -#         = parent_category.name
        -#       -# ↑親カテゴリの表示ここまで↑
        -#       -# ↓子カテゴリの表示ここから↓
        -#       .category-lists__list.child
        -#         - parent_category.get_children.each do |child_category|
        -#           = link_to root_path(child_category), class:"category-lists__list--category" do
        -#             = child_category.name
        -#           -# ↑子カテゴリの表示ここまで↑
        -#           -# ↓孫カテゴリの表示ここから↓
        -#           .category-lists__list.grand-child
        -#             - child_category.get_children.each do |grandchild_category|
        -#               = link_to root_path, class:"category-lists__list--category" do
        -#                 = grandchild_category.name
        -#                 -# ↑孫カテゴリの表示ここまで↑
      .header-bottom-left__button
        = link_to "" do
          = icon "fas", "tags", class:"header-bottom-left__button--red"
          ブランドから探す
    .header-bottom-right
      -# ログイン済みだったら
      - if user_signed_in?
        .header-bottom-right__button
          = link_to "" do
            = icon "fas", "heart", class:"header-bottom-right__button--gray"
            いいね!一覧
        .header-bottom-right__button
          = link_to "" do
            = icon "fas", "bell", class:"header-bottom-right__button--gray"
            お知らせ
        .header-bottom-right__button
          = link_to "" do
            = icon "fas", "check", class:"header-bottom-right__button--gray"
            やることリスト
        .header-bottom-right__button
          = link_to user_path(current_user) do
            = image_tag 'user_noimage.png', class:"header-bottom-right__mypage"
            マイページ
      - else
        = link_to users_select_path,  data: {turbolinks: :false} do
          新規会員登録
        = link_to new_user_session_path, data: {turbolinks: :false}  do
          ログイン

app/views/shared/_side_bar.html.haml
.mypage-side-bar
  .mypage-side-bar-lists
    -# ユーザー管理機能実装時、マイページへのリンクを貼る
    = render partial: 'shared/side_bar_list', locals: {text: "マイページ", path: "#", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "お知らせ", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "いいね！一覧", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "出品する", path: "new_item_path", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "出品した商品---出品中", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "出品した商品---取引中", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "出品した商品---売却済", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "購入した商品---取引中", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "購入した商品---過去の取引", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "ニュース一覧", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "評価一覧", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "ガイド", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "お問い合わせ", path: "", method: ""}
  .mypage-side-bar-lists
    .mypage-side-bar-lists__top
      売上・ポイント
    = render partial: 'shared/side_bar_list', locals: {text: "売上・振込申請", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "ポイント", path: "", method: ""}
  .mypage-side-bar-lists
    .mypage-side-bar-lists__top
      設定
    = render partial: 'shared/side_bar_list', locals: {text: "プロフィール", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "住所変更", path: "", method: ""}
    -# 購入機能を実装時、cards#showへのリンクを貼る
    = render partial: 'shared/side_bar_list', locals: {text: "支払い方法", path: "#", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "メール/パスワード", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "本人情報", path: "", method: ""}
    = render partial: 'shared/side_bar_list', locals: {text: "電話番号の確認", path: "", method: ""}
    -# ユーザー管理機能を実装時、このボタンでログアウトできるようにする
    = render partial: 'shared/side_bar_list', locals: {text: "ログアウト", path: destroy_user_session_path, method: "delete"}
  = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
    = image_tag "side_bar_banner.jpg", class: "side-bar-bottom"

app/views/shared/_side_bar_list.html.haml
= link_to path, method: "#{method}" do
  .mypage-side-bar-lists__list
    .mypage-side-bar-lists__list--left
      = text
    .mypage-side-bar-lists__list--right
      = icon "fas", "chevron-right"

app/views/shared/_sold_out.html.haml
-# 商品が出品中じゃなければ
-if true
  .sold-out
    .sold-out__text
      SOLD