config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'users/select' => 'users/registrations#select'
    get 'users/confirm_phone' => 'users/registrations#confirm_phone'
    get 'users/new_address' => 'users/registrations#new_address'
    post 'users/create_address' => 'users/registrations#create_address' # ここだけ自分で追記
    get 'users/completed' => 'users/registrations#completed'
  end

  resources :users, only: [:show]

  resources :items, only: [:index, :new, :create, :show, :edit,:update,:destroy]  do
    member do
      get "purchase_confirmation"
    end
    collection do
      get 'search'
    end
  end

  resources :categories, only: [:index, :show]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end

  resources :cards, only: [:index, :new]

end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :price, :detail, :condition, :delivery_fee_payer, :delivery_method, :delivery_days, :deal, presence: true
  validates :price, numericality:{greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :images, length: { minimum: 1, maximum: 5, message: "の数が不正です" } 

  belongs_to :category
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: :true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :images, allow_destroy: true, update_only: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  enum condition:{
    "新品、未使用": 0,
    "未使用に近い": 1,
    "目立った傷や汚れなし": 2,
    "やや傷や汚れあり": 3,
    "傷や汚れあり": 4,
    "全体的に状態が悪い": 5
    }

  enum delivery_fee_payer:{
    "送料込み（出品者負担）": 0,
    "着払い（購入者負担）": 1
    }

  enum delivery_method:{
    "未定": 0,
    "らくらくメルカリ便": 1,
    "ゆうメール": 2,
    "レターパック": 3,
    "普通郵便（定形、定形外）": 4,
    "クロネコヤマト": 5,
    "ゆうパック": 6,
    "クリックポスト": 7,
    "ゆうパケット": 8
    }

  enum delivery_days:{
    "1〜2日で発送": 0,
    "2〜3日で発送": 1,
    "4〜7日で発送": 2
    }

  enum deal:{
    "販売中": 0,
    "売り切れ": 1
    }

  scope :new_items, -> { order("created_at DESC").limit(4) }

  def self.search_by_categories(categories)
    return Item.where(category: categories).includes(:images)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :user_is_not_seller, only: [:edit, :update, :destroy]

  def index
    ladies_category = Category.find_by(name: "レディース")
    mens_category = Category.find_by(name: "メンズ")
    kids_category = Category.find_by(name: "ベビー・キッズ")

    ladies_items = Item.search_by_categories(ladies_category.subtree).new_items
    mens_items = Item.search_by_categories(mens_category.subtree).new_items
    kids_items = Item.search_by_categories(kids_category.subtree).new_items

    @new_items_arrays = [
       {category: ladies_category, items: ladies_items},
       {category: mens_category, items: mens_items},
       {category: kids_category, items: kids_items}
      ]
  end

  def show
  end

  def new
    @item = Item.new
    @item.images.build
    render layout: 'no_menu' # レイアウトファイルを指定
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "出品に成功しました"
    else
      redirect_to new_item_path, alert: @item.errors.full_messages
    end
  end

  def edit
    @item.images.build
    render layout: 'no_menu' # レイアウトファイル指定
  end

  def update
    if @item.update(item_params)
      redirect_to root_path, notice: "商品の編集が完了しました。"
    else
      redirect_to edit_item_path(@item), alert: @item.errors.full_messages
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: "商品の削除が完了しました。"
    else
      redirect_to edit_item_path(@item), alert: "商品が削除できませんでした。"
    end
  end

  def purchase_confirmation
    render layout: 'no_menu' # レイアウトファイル指定
  end

  private
  def item_params
    params.require(:item).permit(
      :name,
      :price,
      :detail,
      :condition,
      :delivery_fee_payer,
      :delivery_method,
      :delivery_days,
      :prefecture_id,
      :category_id,
      images_attributes: [:src, :id, :_destroy] 
      ).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def user_is_not_seller
    redirect_to root_path, alert: "あなたは出品者ではありません" unless @item.seller_id == current_user.id
  end

end

app/views/items/_form.html.haml
.block
  .block__menu
    商品の情報を入力
= form_with model: @item, local: true, html: {id: "item_form"} do |f| 
  .block.horizontal-padding-5
    .input-field
      .input-field-main
        = f.label :detail, "出品画像"
        %span.required-true
          必須
        %br
        最大5枚までアップロードできます。
        #selected-item-images
          -# 商品編集の際はプレビューを表示
          - @item.images.each_with_index do |image, i|
            -if image.persisted?
              .item-image{data: {index: i}}
                = image_tag image.src.url, class: "item-image__image"
                .item-image__buttons
                  .item-image__buttons--edit
                    編集
                  .item-image__buttons--delete
                    削除
          #select-image-button
            #select-image-button__text
              クリックしてファイルをアップロード
    #image-file-fields
      = f.fields_for :images do |image|
        = image.file_field :src, accept: "image/*", class: "new-item-image", data: {index: image.index}
        - if image.object.persisted?
          = image.check_box :_destroy, include_hidden: false
    .error-field{data:{column_name: "item_images"}}
  .block.horizontal-padding-5
    .input-field
      .input-field-main
        = f.label :name, "商品名"
        %span.required-true
          必須
        %br
        = f.text_field :name, required: true, placeholder: "PC・携帯どちらも可"
        .error-field{data:{column_name: "name"}}
    .input-field
      .input-field-main
        = f.label :detail, "商品の説明"
        %span.required-true
          必須
        %br
        = f.text_area :detail, required: true, placeholder: "6文字以上", rows: 5
        .error-field{data:{column_name: "detail"}}
  .block.horizontal-padding-5
    .input-field
      .input-field-title
        .input-field-title__text
          商品の詳細
      .input-field-main
        = f.label :category_id, "カテゴリ"
        %span.required-true
          必須
        = f.collection_select :category_id, Category.roots, :id, :name, {include_blank: "---", selected: @item.category&.root_id}, required: true, class: "select-category", id: "parent-category"
        - if @item.category.present?
          = f.collection_select :category_id, @item.category.parent.siblings, :id, :name, {include_blank: "---", selected: @item.category.parent_id}, required: true, class: "select-category"
          = f.collection_select :category_id, @item.category.siblings, :id, :name, {include_blank: "---"}, required: true, class: "select-category"
        .error-field{data:{column_name: "category"}}
        = f.label :condition, "商品の状態"
        %span.required-true
          必須
        %br
        = f.select :condition, Item.conditions.keys, {include_blank: "---"}
  .block.horizontal-padding-5
    .input-field
      .input-field-title
        .input-field-title__text
          配送について
      .input-field-main
        = f.label :delivery_fee_payer, "配送料の負担"
        %span.required-true
          必須
        %br
        = f.select :delivery_fee_payer, Item.delivery_fee_payers.keys, {include_blank: "---"}
        .error-field{data:{column_name: "delivery_fee_payer"}}
        %br
        .input-field-main__delivery-method
          = f.label :delivery_method, "配送の方法"
          %span.required-true
            必須
          %br
          = f.select :delivery_method, Item.delivery_methods.keys, {include_blank: "---"}
          %br
          .error-field{data:{column_name: "delivery_method"}}
        = f.label :prefecture_id, "発送元の地域"
        %span.required-true
          必須
        %br
        = f.collection_select :prefecture_id, Prefecture.all, :id , :name, {include_blank: "---"}, required: true, placeholder: "発送元の地域"
        .error-field{data:{column_name: "delivery_agency"}}
        %br
        = f.label :delivery_days, "発送までの日数"
        %span.required-true
          必須
        %br
        = f.select :delivery_days, Item.delivery_days.keys, {include_blank: "---"}
        .error-field{data:{column_name: "delivery_days"}}
  .block.horizontal-padding-5
    .input-field
      .input-field-title
        .input-field-title__text
          価格（300〜9,999,999）
      .input-field-main
        .input-field-main-price
          .input-field-main-price__left
            = f.label :price, "価格"
            %span.required-true
              必須
          .input-field-main-price__right
            = f.text_field :price, required: true, placeholder: "価格"
            .error-field{data:{column_name: "price"}}
        %hr
        .input-field-main-price
          .input-field-main-price__left
            販売手数料（10%）
          .input-field-main-price__right
            #fee
        %hr
        .input-field-main-price
          .input-field-main-price__left
            販売利益
          .input-field-main-price__right
            #profit
  .block.horizontal-padding-5
    .information
      .information__text
        禁止されている出品、行為を必ずご確認ください。
        %br
        またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        %br
        また、出品をもちまして加盟店規約に同意したことになります。
  .block.horizontal-padding-5
    = f.submit "出品する", class:"button back-red font-white"
    - if action_name == 'edit'
      = link_to item_path(@item), method: :delete do
        .button.back-gray
          商品を削除する
      .horizontal-padding-25
        = link_to "" do
          .button.back-gray
            戻る

app/views/items/_item.html.haml
= link_to item_path(item), data:{turbolinks: false}  do
  .item
    - if item.deal != "販売中"
      = render partial: 'shared/sold_out'
    .item-top
      = image_tag item.images.first&.src&.url, class: "item-top__image"
      .item-top__price
        ¥#{item.price}
    .item-bottom
      .item-bottom__name
        = item.name
      .item-bottom-price-good
        .item-bottom-price-good__price
        = icon "fas", "heart", class:"item-bottom-price-good__good"

app/views/items/edit.haml
= render 'form'

app/views/items/index.html.haml
.campaigns
  .campaigns-app
    .index-campaign.horizontal-padding-15
      = image_tag 'campaign_bg.jpg', class: "campaign_bg"
      .index-campaign__left.index-campaign__banner-inside-parts
        %p.index-campaign__left-top
          スマホでカンタン
          %br
          フリマアプリ
        %p.index-campaign__left-bottom
          メルカリはスマホカメラからすぐに出品できる
          %br
          購入時も安心な独自システムのアプリです
        = image_tag 'app-store.svg', class: "index-campaign__banner-inside-parts"
        = image_tag 'google-play.svg', class: "index-campaign__banner-inside-parts"
      = image_tag 'campaign_bg_phone.png', class: "index-campaign__phone index-campaign__banner-inside-parts"
  .campaigns-camp
    .index-campaign.horizontal-padding-15
      = image_tag 'banner-camp.jpg', class: "campaign_bg"
.pickups-header
  人気のカテゴリー
  .pickups-header__category-names
    - @new_items_arrays.each do |new_items|
      = link_to category_path(new_items[:category]) do
        .pickups-header__category-names--category-name
          = new_items[:category].name
.pickups.horizontal-padding-15
  %br
  - @new_items_arrays.each do |new_items|
    .pickup
      %span.pickup__name
        = new_items[:category].name
        新着アイテム
      = link_to category_path(new_items[:category]) do
        %span.pickup__display-all
          もっと見る >
      .pickup__items
        = render new_items[:items]

app/views/items/new.html.haml
= render 'form'

app/views/items/purchase_confirmation.html.haml
.block.horizontal-padding-25
  .block__menu
    購入内容の確認
.block.horizontal-padding-25
  .block__main
    .item-purchase-confirmation
      .item-purchase-confirmation__image-and-name
        = image_tag ""
        .item-purchase-confirmation__image-and-name--name
          商品名hoge
      .item-purchase-confirmation__price
        .item-purchase-confirmation__price--yen
          ¥1000
        .item-purchase-confirmation__price--fee
          \(税込み)
    .button.back-gray
      ポイントはありません
    #amount
      #amount__left
        支払金額
      #amount__right
        ¥1000
    - unless @card
      .font-red
        配送先と支払い方法の入力を完了してください。
    = link_to "", method: :post do
      .button{class: "#{'back-red' if @card}" }
        購入する
.block.horizontal-padding-25
  .block__menu-left
    配送先
  .block__main
    〒111-2222
    %br
    東京都　渋谷区神南1丁目12−16
    %br
    フリマ　太郎
  .block__menu-right
    = link_to "" do
      変更する >
.block.horizontal-padding-25
  .block__menu-left
    支払い方法
  .block__main
    #card-data
      - if @card
        = @card[:last4]
        %br
        = @card[:exp_month]
        \/
        = @card[:exp_year]
        %br
        = @card[:brand]
      - else
        \/
  .block__menu-right
    = link_to "", data: {turbolinks: false} do
      変更する >

app/views/items/search.html.haml
.search-view.horizontal-padding-15
  -# ransack導入時に専用フォームヘルパーに置き換える
  = form_with do |f|
    = f.select(:hoge, [], {include_blank: "並び替え"}, class: "search-form__input")
    .search-form
      .search-form__title
        詳細検索
      /// 商品名
      = icon "fas", "plus"
      = f.label :hoge, "キーワードを追加する", {class: "search-form__label"}
      = f.search_field :hoge, placeholder: "例）値下げ", class: "search-form__input"
      /// カテゴリー
      = icon "fas", "list"
      = f.label :hoge, 'カテゴリーを選択する',{class: "search-form__label"}
      .search-form__categories
        = f.collection_select(:hoge, [], :hoge , :hoge, {include_blank: "すべて"}, {class: "select-category", id: "item_parent_category_id"})
        /// 親カテゴリーが選択されていたら子カテゴリーを追加する
        - if true
          = f.collection_select(:hoge, [], :hoge , :hoge, {include_blank: "すべて"}, {class: "select-category search-form-added"})
        /// 子カテゴリーが選択されていたら孫カテゴリーを追加する
        - if true
          .select-category.search-form-added
            .search-checkboxes.search-form-added
              = f.collection_check_boxes(:hoge, [], :hoge , :hoge, {}, {class: "select-category search-form-added"})
      /// 価格
      = icon "fas", "yen-sign"
      = f.label :hoge, '価格', {class: "search-form__label"}
      = f.select :hoge, [], include_blank: '指定なし'
      .search-form__price-range
        = f.text_field :hoge, placeholder: "¥ Min"
        〜
        = f.text_field :hoge, placeholder: "¥ Max"
      /// 状態
      = icon "fas", "star"
      = f.label :hoge, '状態', {class: "search-form__label"}
      .search-checkboxes
        = f.collection_check_boxes :hoge, [], :hoge, :hoge
      /// 送料の負担者
      = icon "fas", "truck"
      = f.label :hoge, '送料負担', {class: "search-form__label"}
      .search-checkboxes
        = f.collection_check_boxes :hoge, [], :hoge, :hoge
      /// 販売状況
      = icon "fas", "shopping-cart"
      = f.label :hoge, '販売状況', {class: "search-form__label"}
      .search-checkboxes
        = f.collection_check_boxes :hoge, [], :hoge, :hoge
      /// 送信
      .search-form__buttons
        .search-form__buttons--clear.button.back-gray
          クリア
        = f.submit "完了", class:"search-form__buttons--submit button back-red"
  .search-results
    -# 検索結果があれば
    - if false
      = render partial: "items/item", collection: @items, as: :item
      #pagenation
        = paginate(@items)
    - else
      .result-none
        .result-none__title
          検索結果
        .result-none__text
          該当する商品が見つかりません。検索条件を変えて、再度お試しください。

app/views/items/show.html.haml
.block.horizontal-padding-25
  .block__menu
    = @item.name
  .item-show
    - if @item.deal != "販売中"
      = render partial: 'shared/sold_out', locals:{item: @item}
    .item-show__images-data
      .item-images
        .item-images__main
          .item-images__main-images
            - @item.images.each_with_index do |image, i|
              = image_tag image.src.url, data: {big_image_index: i}
        .item-images__mini-images
          - @item.images.each_with_index do |image, i|
            = image_tag image.src.url, data: {mini_image_index: i}
      %table.item-data
        %tr.item-data__row
          %th.item-data__row--title
            出品者
          %td.item-data__row--value
            = @item.seller.nickname
        %tr.item-data__row
          %th.item-data__row--title
            カテゴリ
          %td.item-data__row--value
            = link_to @item.category.root.name, ""
            %br
            = link_to ">#{@item.category.parent.name}", "" 
            %br
            = link_to ">#{@item.category.name}", ""
        %tr.item-data__row
          %th.item-data__row--title
            商品の状態
          %td.item-data__row--value
            = @item.condition
        %tr.item-data__row
          %th.item-data__row--title
            配送料の負担
          %td.item-data__row--value
            = @item.delivery_fee_payer
        %tr.item-data__row
          %th.item-data__row--title
            配送の方法
          %td.item-data__row--value
            = @item.delivery_method
        %tr.item-data__row
          %th.item-data__row--title
            配送元地域
          %td.item-data__row--value
            = @item.prefecture.name
        %tr.item-data__row
          %th.item-data__row--title
            発送日の目安
          %td.item-data__row--value
            = @item.delivery_days
    .item-show__price
      .item-show__price--left
        ¥#{@item.price}
      .item-show__price--middle
        （税込）
      .item-show__price--right
        送料込み
    - if @item.seller != current_user 
      = link_to "" do
        .button.back-red
          購入画面に進む
    - if @item.seller == current_user 
      = link_to edit_item_path(@item) do
        .button.back-gray
          商品を編集する
      .item-show__detail
        = @item.detail