config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'users/select' => 'users/registrations#select'
    get 'users/confirm_phone' => 'users/registrations#confirm_phone'
    get 'users/new_address' => 'users/registrations#new_address'
    post 'users/create_address' => 'users/registrations#create_address' # ここだけ自分で追記
    get 'users/completed' => 'users/registrations#completed'
  end

  resources :users, only: [:show]

  resources :items, only: [:index, :new, :create, :show, :edit,:update,:destroy]  do
    member do
      get "purchase_confirmation"
    end
    collection do
      get 'search'
    end
  end

  resources :categories, only: [:index, :show]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end

  resources :cards, only: [:index, :new]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSecond
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render 'shared/flash'
  = render 'shared/header'
  = yield
  = link_to new_item_path, data:{turbolinks: false} do
    .sell-button
      .sell-button__text
        出品
      = icon "fas", "camera", class:"sell-button__icon"
  = render 'shared/footer'

app/views/layouts/no_menu.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSecond
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
%body
  = render 'shared/flash'
  .horizontal-padding-25
    %header.header-no-menu
      = link_to root_path do
        = image_tag 'top-logo.svg', class: "logo"
      -if @progress
        .progress-bar
          .progress
            .progress-title{class: "#{'doing' if @progress == 1}"}
              会員情報
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 1}"}
              .progress-node__line{class: "#{'done' if @progress >= 2}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 2}"}
              電話番号認証
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 2}"}
              .progress-node__line{class: "#{'done' if @progress >= 3}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 3}"}
              お届け先住所入力
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 3}"}
              .progress-node__line{class: "#{'done' if @progress >= 4}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 4}"}
              支払い方法
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 4}"}
              .progress-node__line{class: "#{'done' if @progress >= 5}"}
          .progress
            .progress-title{class: "#{'doing' if @progress == 5}"}
              完了
            .progress-node
              .progress-node__circle{class: "#{'done' if @progress >= 5}"}
    = yield
    %footer.footer-no-menu
      %nav
        %ul
          = link_to "" do
            %li
              プライバシーポリシー
          = link_to "" do
            %li
              メルカリ利用規約
          = link_to "" do
            %li
              特定商取引に関する表記
      = image_tag 'bottom-logo.svg', class: "logo"